name: Get latest release versions

on:
  push:
    paths:
      - ".github/workflows/schedule.yml"
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 1
      - name: Fetch release versions
        run: |
          find . -maxdepth 1 -mindepth 1 -type d | while read app; do
            version=$(bash "./${app}/latest-version.sh")
            echo "${version}" | tee "${app}/.version"
          done
      - name: Add, commit and push to applications version file
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config --global user.name "Devin Buhl"
            git config --global user.email "onedr0p@users.noreply.github.com"
            git add -A
            git commit -sam "Adding new release versions" || exit 0
            git push
          fi
